# Must be pytorch-base or pytorch-openvino-base
ARG BASE_IMG

FROM intel/intel-extension-for-pytorch:2.1.20-xpu as pytorch
RUN echo "Building pytorch image"
ENV BASE_IMG=pytorch

FROM intel/intel-optimized-pytorch:2.2.0-pip-base as pytorch-openvino
RUN echo "Building Pytorch+Openvino image"
USER root
RUN pip install openvino scipy
#RUN apt update; apt install gpg -y; sleep 5; wget -qO - https://repositories.intel.com/gpu/intel-graphics.key | gpg --yes --dearmor --output /usr/share/keyrings/intel-graphics.gpg; echo "deb [arch=amd64,i386 signed-by=/usr/share/keyrings/intel-graphics.gpg] https://repositories.intel.com/gpu/ubuntu jammy client" | tee /etc/apt/sources.list.d/intel-gpu-jammy.list; apt update; apt install -y intel-opencl-icd intel-level-zero-gpu level-zero 
# Install latest gpu compute drivers for kernel 6.5 not working with opencl
RUN apt update; apt install -y ocl-icd-libopencl1; mkdir neo; cd neo; wget https://github.com/intel/intel-graphics-compiler/releases/download/igc-1.0.16900.23/intel-igc-core_1.0.16900.23_amd64.deb; wget https://github.com/intel/intel-graphics-compiler/releases/download/igc-1.0.16900.23/intel-igc-opencl_1.0.16900.23_amd64.deb; wget https://github.com/intel/compute-runtime/releases/download/24.22.29735.20/intel-level-zero-gpu-dbgsym_1.3.29735.20_amd64.deb; wget https://github.com/intel/compute-runtime/releases/download/24.22.29735.20/intel-level-zero-gpu_1.3.29735.20_amd64.deb; wget https://github.com/intel/compute-runtime/releases/download/24.22.29735.20/intel-opencl-icd-dbgsym_24.22.29735.20_amd64.deb; wget https://github.com/intel/compute-runtime/releases/download/24.22.29735.20/intel-opencl-icd_24.22.29735.20_amd64.deb; wget https://github.com/intel/compute-runtime/releases/download/24.22.29735.20/libigdgmm12_22.3.19_amd64.deb; dpkg -i *.deb
# intel-media-va-driver-non-free libmfx1 libmfxgen1 libvpl2 libegl-mesa0 libegl1-mesa libegl1-mesa-dev libgbm1 libgl1-mesa-dev libgl1-mesa-dri libglapi-mesa libgles2-mesa-dev libglx-mesa0 libigdgmm12 libxatracker2 mesa-va-drivers mesa-vdpau-drivers mesa-vulkan-drivers va-driver-all vainfo 

ENV BASE_IMG=pytorch-openvino

FROM ${BASE_IMG} as final
WORKDIR /app
USER root
RUN pip install --upgrade pip setuptools

COPY requirements-intel.txt .

RUN pip3 install -r requirements-intel.txt --timeout 1000

ARG MODEL_NAME
COPY download_model.py .
COPY download_model-openvino.py .
RUN if [ "$BASE_IMG" = "pytorch" ]; then python3 ./download_model.py; else python3 ./download_model-openvino.py; fi

COPY . .

ENTRYPOINT ["/bin/sh", "-c"]
CMD ["uvicorn app:app --host 0.0.0.0 --port 8080"]
